#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

yum -y install https://repo.mysql.com/mysql-community-release-el7.rpm
yum -y install mysql-community-server

# move the config dir for now but leave /etc/my.cnf alone
# ln -s creates problems for the systemd script
mkdir /etc/mysql
mv /etc/my.cnf.d /etc/mysql/conf.d
chown -R mysql:mysql /etc/mysql
