#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

# avoid some dep conflicts here
yum -y remove mariadb-libs mariadb-server

# install vendor release repo
yum -y install http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm

# The fix to make versions of percona-xtrabackup > v2.2 work with Trove
# was put into the mysql guestagent code for Mitaka. There are no current
# plans to backport so we need to make sure the guest generated when the
# tests are run for Kilo or Liberty get the 2.2 verson of PXB
if [[ $BRANCH_OVERRIDE == "stable/kilo" || $BRANCH_OVERRIDE == "stable/liberty" ]]; then
    PXB_VERSION_OVERRIDE="-22"
fi

yum -y install socat

# we'll install the config first and modify that
# for the locations Trove expects
yum -y install Percona-XtraDB-Cluster-shared-56

sed -i 's|!includedir[ \t]*/etc/my.cnf.d|!includedir /etc/mysql/conf.d|' /etc/my.cnf

# move conf dir
mkdir /etc/mysql
mv /etc/my.cnf.d /etc/mysql/conf.d
chcon -Rv --type=mysqld_etc_t /etc/mysql

groupadd -r mysql
useradd -M -r -d /var/lib/mysql -s /bin/bash -c "MySQL server" \
  -g mysql mysql
usermod -g mysql mysql

yum -y install Percona-XtraDB-Cluster-client-56 Percona-XtraDB-Cluster-galera-25 \
	 percona-xtrabackup${PXB_VERSION_OVERRIDE}

# cluster template unfortunately has an Ubuntu path
ln -s /usr/lib64/galera3/libgalera_smm.so /usr/lib/libgalera_smm.so

# now install server using rpm but don't let
# the server post scriptlet run
rpm -ivh --nopost `yumdownloader -q --urls Percona-XtraDB-Cluster-server-56`
/usr/bin/mysql_install_db --rpm --user=mysql --datadir=/var/lib/mysql

# sock file needs to be written here too
# but pre script sets mysql:mysql
chown -R mysql:root /var/lib/mysql

# ensure Trove manages the boostrap stuff (new wsrep cluster)
systemctl disable mysql
