#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

# just in case
yum -y remove mariadb-server

# install vendor release repo
yum -y install http://www.percona.com/downloads/percona-release/redhat/0.1-3/percona-release-0.1-3.noarch.rpm

# The fix to make versions of percona-xtrabackup > v2.2 work with Trove
# was put into the mysql guestagent code for Mitaka. There are no current
# plans to backport so we need to make sure the guest generated when the
# tests are run for Kilo or Liberty get the 2.2 verson of PXB
if [[ $BRANCH_OVERRIDE == "stable/kilo" || $BRANCH_OVERRIDE == "stable/liberty" ]]; then
    PXB_VERSION_OVERRIDE="-22"
fi

yum -y install percona-toolkit Percona-Server-shared-56 Percona-Server-server-56 Percona-Server-test-56 Percona-Server-client-56 percona-xtrabackup${PXB_VERSION_OVERRIDE}

# there's a mistaken assumption that the config
# dir will already be there for the trove template
mkdir -p /etc/mysql/conf.d
chown -R mysql:mysql /etc/mysql

# another package-specific adjustment
mkdir -p /var/lib/mysql/data
sed -i "s|datadir=/var/lib/mysql|datadir=/var/lib/mysql/data|" /etc/my.cnf
